### PR TITLE
fix composer install command

### PR DESCRIPTION
**Pull request by Maikel-Koek**
## Purpose of this pull request
 
This pull request (PR) ...
 
## Affected Support KB pages
 

 
List the affected pages on support.magento.com (URLs).

### CODE REVIEW

**Review by barnato-v — APPROVED** [review]
@Maikel-Koek Thank you for your review. This looks good.

**Comment by barnato-v** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@barnato-v the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-Maikel-Koek-knowledge-base-170`.

**Comment by barnato-v** [comment]
@Maikel-Koek Apologies for how long this took. Your suggested formatting correction was lost I think due to repo migration - but change was made here https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/troubleshooting/miscellaneous/github-token-issue-and-composer-key-procedures.html

**Pull request closed without merging**
