### PR TITLE
Corrected versions for the existing patch

### PR DESCRIPTION
**Pull request by katmoon**
## Purpose of this pull request
 
This pull request (PR) updates the applicable versions for the existing QPT patch
 
## Affected Support KB pages
 
https://support.magento.com/hc/en-us/articles/4402390637453

### CODE REVIEW

**Review by jmenn — APPROVED** [review]

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Review by jmenn — APPROVED** [review]

**Comment by almarchenko** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@almarchenko the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-katmoon-knowledge-base-128`.

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@jmenn the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-katmoon-knowledge-base-128`.

**Comment by jmenn** [comment]
https://jira.corp.adobe.com/browse/MSKB-1544

**Pull request merged**
