### PR TITLE
Update Checking currencies information

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request
 
This pull request (PR) addresses #96 
 
## Affected Support KB pages
 
https://support.magento.com/hc/en-us/articles/360041456192#zd-accordion-2

### CODE REVIEW

**Review by ak77-prime — CHANGES_REQUESTED** [review]
The command doesn't work:

```
$ php74 bin/magento config:show currency
The "currency" path doesn't exist. Verify and try again.
```

**Comment by BarnyShergold** [comment]
> The command doesn't work:
> 
> ```
> $ php74 bin/magento config:show currency
> The "currency" path doesn't exist. Verify and try again.
> ```

The command has been updated to be correct : `php bin/magento config:show currency/options/base`

**Comment by ak77-prime** [comment]
the command works ``bin/magento  config:show currency/options/base``

**Comment by BarnyShergold** [comment]
> the command works `bin/magento config:show currency/options/base`
> 
> however, for the purposes of the Advanced Reporting Troubleshooter, it would only return the default scope regardless of whether multiple base currencies have been configured, and Advanced Reporting is only supposed to work when only 1 base currency had been used throughout the lifetime of the Magento instance

You are correct, I thought I had this correct. The problem therefore with using the bin/magento command to find all the  CURRENT base currencies is that the admin needs to know all the scope codes for all the non-default sites and then run the command for each - which is going to be massively time consuming.

I propose ditching the bin/magento command and simply use this SQL statement -
`SELECT value FROM `core_config_data` WHERE path = 'currency/options/base';`

This will give al the information in a nice simple way. After all, if they don't find more than 1 currency they still need to run the second SQL statement.

**Comment by ak77-prime** [comment]
> You are correct, I thought I had this correct. The problem therefore with using the bin/magento command to find all the CURRENT base currencies is that the admin needs to know all the scope codes for all the non-default sites and then run the command for each - which is going to be massively time consuming.
> 
> I propose ditching the bin/magento command and simply use this SQL statement - `SELECT value FROM core_config_data WHERE path = 'currency/options/base';`
> 
> This will give al the information in a nice simple way. After all, if they don't find more than 1 currency they still need to run the second SQL statement.

sounds good

**Comment by BarnyShergold** [comment]
@ak77-prime - How does this look now?

**Review by ak77-prime — APPROVED** [review]

**Comment by jmenn** [comment]
We in the Support KB team have noted that the changed info was approved.

However, merging this info will cause at least a couple crucial formatting setups to break, causing some major formatting errors on the troubleshooter page. -- So before merging we want to clarify internally that these formatting fixes are correct, to avoid breaking the page when it gets published. We will get back to this right after the fix clarification is complete. Thank you!

**Review by almarchenko — APPROVED** [review]

**Review by barnato-v — APPROVED** [review]

**Comment by m2-github-services** [comment]
@barnato-v the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-BarnyShergold-knowledge-base-104`.

**Pull request merged**
