### PR TITLE
Converting filenames to the correct format

### LINKED ISSUE #60: Some file names are NOT in the correct format
# General issue
  
## Description
All the letters in the file names should be in **lower case**.  Need to change those that are in upper case.

1. [MDVA-34680-customer-account-created-time-is-not-filtered-correctly-in-customers-grid.md](https://github.com/magento/knowledge-base/blob/main/src/support-tools/patches-available-in-mqp-tool/MDVA-34680-customer-account-created-time-is-not-filtered-correctly-in-customers-grid.md)
1. [MDVA-37068-incorrect-tax-rate-displays-on-checkout-for-virtual-products.md](https://github.com/magento/knowledge-base/blob/main/src/support-tools/patches-available-in-mqp-tool/MDVA-37068-incorrect-tax-rate-displays-on-checkout-for-virtual-products.md)
1. [MDVA-38308-error-after-adding-vimeo-videos-to-disabled-products.md](https://github.com/magento/knowledge-base/blob/main/src/support-tools/patches-available-in-mqp-tool/MDVA-38308-error-after-adding-vimeo-videos-to-disabled-products.md)
1. [MDVA-38468-error-when-saving-cms-pages.md](https://github.com/magento/knowledge-base/blob/main/src/support-tools/patches-available-in-mqp-tool/MDVA-38468-error-when-saving-cms-pages.md)

## Possible solutions

mdva-34680-customer-account-created-time-is-not-filtered-correctly-in-customers-grid.md
mdva-37068-incorrect-tax-rate-displays-on-checkout-for-virtual-products.md
mdva-38308-error-after-adding-vimeo-videos-to-disabled-products.md
mdva-38468-error-when-saving-cms-pages.md

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Fixes #60

### CODE REVIEW

**Review by BarnyShergold — APPROVED** [review]
That's awesome!

Please can you sign the Adobe CLA to allow progress? You only ever need to do this once.

Thanks!

**Comment by mohitsaxenaknoldus** [comment]
> That's awesome!
> 
> Please can you sign the Adobe CLA to allow progress? You only ever need to do this once.
> 
> Thanks!

I just did that. I think it passed that.

**Comment by BarnyShergold** [comment]
Looks good!

**Comment by mohitsaxenaknoldus** [comment]
> Looks good!

Thanks! How can I get this merged?

**Comment by BarnyShergold** [comment]
> > Looks good!
> 
> Thanks! How can I get this merged?

We wait for the Adobe team to approve and handle. Takes a few days to a week - this is a new repo for contribution and they are still sorting out processes.

**Comment by Rinn22** [comment]
Thanks you @BarnyShergold  and @mohitsaxenaknoldus. The changes look good. I'm gonna add label and import this PR to our internal  repo.  We will merge the PR internally.

**Review by Rinn22 — APPROVED** [review]

**Review by Rinn22 — APPROVED** [review]

**Comment by mohitsaxenaknoldus** [comment]
> Thanks you @BarnyShergold and @mohitsaxenaknoldus. The changes look good. I'm gonna add label and import this PR to our internal repo. We will merge the PR internally.

Thanks!

**Comment by Rinn22** [comment]
Hey @BarnyShergold, can you approve this one more time. For some reason I cannot add label.

**Review by BarnyShergold — APPROVED** [review]

**Comment by Rinn22** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by Rinn22** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by Rinn22** [comment]
`@magento import code to magento-kb/knowledge-base`

**Comment by tanay-sharma** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by magento-engcom-team** [comment]
@barnato-v the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-81`.

**Pull request merged**
