### PR TITLE
Test-import-Public-PR

### PR DESCRIPTION
**Pull request by Rinn22**
This is a test to see if importing public PR works or not.

### CODE REVIEW

**Comment by Rinn22** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by Rinn22** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by lenaorobei** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by magento-engcom-team** [comment]
@lenaorobei the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-85`.

**Comment by magento-engcom-team** [comment]
@Rinn22 the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-85`.

**Comment by tanay-sharma** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by magento-engcom-team** [comment]
@tanay-sharma the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-85`.

**Pull request closed without merging**
