### PR TITLE
Update/contribution linting

### PR DESCRIPTION
**Pull request by BarnyShergold**
## Purpose of this pull request
 
This pull request (PR) adds information about testing contributions locally for linting issues.
 
## Affected Support KB pages
 
CONTRIBUTING.md

### CODE REVIEW

**Review by barnato-v — COMMENTED** [review]
@BarnyShergold Hi Barny,

Would it be also worth mentioning in this file that the user can install a package with Atom called linter-markdownlint - which highlights your linting errors in the md file so you can fix them before you create a PR? - see this link to learn more about it https://atom.io/packages/linter-markdownlint

**Comment by BarnyShergold** [comment]
> @BarnyShergold Hi Barny,
> 
> Would it be also worth mentioning in this file that the user can install a package with Atom called linter-markdownlint - which highlights your linting errors in the md file so you can fix them before you create a PR? - see this link to learn more about it https://atom.io/packages/linter-markdownlint

Seems like a good idea - so I've added it :)

**Comment by barnato-v** [comment]
@BarnyShergold Hi Barny, I apologize for the lack of progress on this (I wanted to merge this PR). I have emailed our team's contact on this to try to get this resolved (created a ticket with the pr that was merged which didn't result in you getting points). This is both for you but also to ensure that all other future contributors get their points.

**Comment by almarchenko** [comment]
@barnato-v  Hey Vicky, I think Barny didn't get points as a maintainer last time, but he should get points ok as a contributor, so we can proceed with importing and merging this PR. Do you want me to do this?

**Comment by BarnyShergold** [comment]
> @barnato-v Hey Vicky, I think Barny didn't get points as a maintainer last time, but he should get points ok as a contributor, so we can proceed with importing and merging this PR. Do you want me to do this?

Hi - I can confirm that I just got maintainer points for PR #47  but not had any for 46 & 48

**Comment by almarchenko** [comment]
> > @barnato-v Hey Vicky, I think Barny didn't get points as a maintainer last time, but he should get points ok as a contributor, so we can proceed with importing and merging this PR. Do you want me to do this?
> 
> Hi - I can confirm that I just got maintainer points for PR #47 but not had any for 46 & 48
@BarnyShergold  I suspect this is because the #47 was still open when the maintainers points system got activated, while #46 and #48 were already merged. I will double-check with our tech team.

**Comment by almarchenko** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by magento-engcom-team** [comment]
@almarchenko the branch with code successfully imported into`magento-kb/knowledge-base` repository. Branch name: `imported-magento-knowledge-base-49`.

**Pull request merged**
