### PR TITLE
Update magento-upgrade-compact-to-dynamic-tables-2.2.x-2.3.x-2.4.x.md

### PR DESCRIPTION
**Pull request by cmijaresb**
Changed single quotes format from ’ to '.

## Purpose of this pull request
 
This pull request (PR) ...
 
## Affected Support KB pages
 

 
List the affected pages on support.magento.com (URLs).

### CODE REVIEW

**Review by jmenn — APPROVED** [review]

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@jmenn the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-cmijaresb-knowledge-base-138`.

**Comment by jmenn** [comment]
https://support.magento.com/hc/en-us/articles/360048389631

**Comment by jmenn** [comment]
https://github.com/magento import code to magento-kb/knowledge-base

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@jmenn the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-cmijaresb-knowledge-base-138`.

**Comment by jmenn** [comment]
Thanks, @cmijaresb! We've merged (added) these changes!

**Pull request merged**
