### PR TITLE
Update mdva-41236-unable-to-create-new-or-edit-existing-scheduled-sta…

### PR DESCRIPTION
**Pull request by katmoon**
## Purpose of this pull request

Correct fix version
 
## Affected Support KB pages
 
https://support.magento.com/hc/en-us/articles/4413127293965-MDVA-41236-Unable-to-create-new-or-edit-existing-scheduled-updates-for-product

### CODE REVIEW

**Review by jmenn — APPROVED** [review]

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@jmenn the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-katmoon-knowledge-base-130`.

**Comment by jmenn** [comment]
@magento import code to magento-kb/knowledge-base

**Comment by m2-github-services** [comment]
@jmenn the branch with the code is successfully imported into the `magento-kb/knowledge-base` repository. Branch name: `imported-katmoon-knowledge-base-130`.

**Pull request merged**
